[package]
name = "rate-limiter-rs"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
redis = "0.22.2"
thiserror = "1.0.38"

[dev-dependencies]
rand = "0.8.5"
rstest = "0.16.0"
uuid = { version = "1.2.2", features = [ "v4", "fast-rng", "macro-diagnostics" ]}
